name: Legito.Mobile
description: "Legito Mobile Application"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # BU SATIR OLMALI
    sdk: flutter       
  http: ^1.1.0
  jwt_decode: ^0.3.1
  intl: 0.19.0
  # file_picker: ^5.5.0
  image_picker: ^1.0.4
  stop_watch_timer: ^2.0.0
  fl_chart: ^0.68.0
  url_launcher: ^6.2.5
  video_player: ^2.8.6  
  chewie: ^1.7.5      
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences:
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/appIcon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
