name: legitoproject
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # BU SATIR OLMALI
    sdk: flutter       
  http: ^1.1.0
  jwt_decode: ^0.3.1
  intl: 0.19.0
  fl_chart: ^0.68.0
  url_launcher: ^6.2.5
  video_player: ^2.8.6  
  chewie: ^1.7.5      
  image_picker: 
  font_awesome_flutter: ^10.6.0
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  shared_preferences:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
